# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.0.4
_src_path: gh:Comunitea/doodba-copier-template
backup_dst: ''
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ''
odoo_dbfilter: ^prod
odoo_initial_lang: es_ES
odoo_listdb: true
odoo_listdb_staging: true
odoo_oci_image: ''
odoo_proxy: other
odoo_version: 19.0
paths_with_crawlers:
- /web/image/website
paths_without_crawlers:
- /web
- /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod
postgres_exposed: true
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: '17'
project_author: Comunitea
project_license: AGPL-3.0-or-later
project_name: doodba_19
smtp_default_from: ''
smtp_relay_host: ''

