# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v3.3.3
_src_path: gh:Comunitea/doodba-copier-template
backup_deletion: false
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod: null
domains_test: null
gitlab_url: null
odoo_dbfilter: .*
odoo_initial_lang: es_ES
odoo_listdb: true
odoo_oci_image: null
odoo_proxy: other
odoo_version: 14.0
paths_without_crawlers:
- /web
- /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod
postgres_exposed: true
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: '14'
project_author: Javier
project_license: AGPL-3.0-or-later
project_name: doodba_odoo14
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null
smtp_relay_version: '10'

