version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: ".*"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_ES"
      PYTHONPATH: /opt/odoo/custom/src/odoo
    depends_on:
      - db
    networks:
      default:
    ports:
      - "0.0.0.0:16899:6899"
      - "0.0.0.0:16069:8069"
      - "0.0.0.0:16072:8072"
    labels:
      doodba.domain.main: ""

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  filestore:
  db:
